version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    networks:
      - app_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    networks:
      - app_network


volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge