apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  api-url: "http://localhost:30000/api"  
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2hhcnNodHJpcGF0aGkxMjM=
  mongo-uri: bW9uZ29kYitzcnY6Ly8yazIyY3NhaTIyMTE5ODI6b0cybVVaQ2NVTWJncWJpVUBjbHVzdGVyMC52c2ZmZ3FwLm1vbmdvZGIubmV0Lw==